CREATE TABLE CLIENTES(
    CNPJ VARCHAR2(14) NOT NULL,
    RAZAO_SOCIAL VARCHAR2(100) NOT NULL,
    USUARIO VARCHAR2(100) NOT NULL,
    SENHA VARCHAR2(100) NOT NULL,
    STATUS VARCHAR2(100) NOT NULL

);